project:
  type: website

website:
  title: JGI Data Science Handbook
  navbar:
    background: primary
  sidebar:
    contents: auto
    style: docked
    # collapse-level: 1
    tools:
      - icon: globe2
        href: "https://www.bristol.ac.uk/golding/"
      - icon: folder
        href: "https://uob.sharepoint.com/teams/grp-jeangoldinginstituteteam/Shared Documents/"
      - icon: github
        href: "https://github.com/jgibristol"
      - icon: twitter
        href: "https://twitter.com/jgibristol"
      - icon: youtube
        href: "https://www.youtube.com/@jgibristol"
      - icon: linkedin
        href: "https://www.linkedin.com/showcase/jean-golding-institute-showcase/"

format:
  html:
    theme: [cosmo, styles.scss]
    toc: true
  
# Recommended by https://quarto.org/docs/publishing/github-pages.html#freezing-computations
# (although we're not expecting to be executing any code)
execute:
  freeze: auto
